FROM node:20

WORKDIR /app

COPY package*.json /app/

# RUN npm config set registry https://registry.npmmirror.com

RUN npm install

# RUN npx -y playwright install --with-deps

COPY ./ /app/

ARG VITE_API_URL=${VITE_API_URL}
